services:
  user:
    build:
      context: .
    ports:
      - 8083:8080
    environment:
      - DATABASE_URL=postgres://user:secret@db:5432/user
      - ROCKET_DATABASES=${ROCKET_DATABASES}
      - YONDER_JWT_SECRET=${YONDER_JWT_SECRET}
    networks:
      - web_app-net
      - db-net
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
     - db:/var/lib/postgresql/data
    networks:
      - db-net
networks:
  db-net:
    driver: bridge
  web_app-net:
    external: true
volumes:
  db:
    driver: local
